package user.data.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "ProductInfo")
public class User {
    private String id;
    private String name;
    private List<String> files;

    public User() {
    }

    public User(String id, String name) {
        this.name = name;
        this.id = id;
    }

    public User(String id, String name, List<String> files) {
        this.id = id;
        this.name = name;
        this.files = files;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public List<String> getFiles() {
        return files;
    }

}
